activation: relu
aggr: mean
center_conformations: true
center_max_radius: 30.0
config: null
data_dir: data
dataset: d3pm
diffusivity_schedule: constant
distance_embed_dim: 32
drift_weight: 1.0
dropout_p: 0.2
early_stop_goal: min
early_stop_metric: val_loss
edge_fdim: 0
ema_decay_rate: 0.8
eval_every: 1
grad_clip_value: 5.0
group_name: CONF_TP_MODEL
h_dim: 32
inference_every: 1
inference_goal: min
inference_metric: val_inference_rmsd
inference_steps: 10
leakyrelu_slope: 0.01
log_dir: logs
log_every: 10
lr: 0.001
max_diffusivity: 1.0
max_distance: 80.0
max_neighbors: 40
max_radius: 40.0
model_name: tensor-prod
n_conv_layers: 3
n_epochs: 10000
n_s: 30
n_v: 10
node_fdim: 145
num_inference_proteins: 5
num_workers: 1
optim_name: adamw
reg_weight_T: 1.0
reg_weight_t: 10.0
resolution: c_alpha
run_name: CONF_TP_MODEL-gia1ordl
samples_per_protein: 10
samples_per_protein_train: 10
scheduler: plateau
scheduler_mode: min
scheduler_patience: 50
sh_lmax: 2
shared_layers: false
task: conf
timestep_emb_dim: 32
timestep_embed_dim: 32
timestep_embed_type: sinusoidal
train_bs: 2
transform: null
use_drift_in_doobs: false
use_grad_noise: false
val_bs: 1
wandb_entity: vsomnath
wandb_mode: online
weight_decay: 0.01
